backend:
  name: github
  repo: algorithmia-netlify/testing
collections:
  - name: 'page'
    label: 'Page'
    folder: 'pages'
    create: true
    preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - label: 'Content'
        name: 'content'
        widget: 'list'
        types:
          - label: 'Markdown'
            name: 'markdown'
            widget: 'object'
            fields:
              - { label: 'content', name: 'content', widget: 'markdown' }
          - label: 'Code Sample'
            name: 'code-sample'
          widget: 'object'
            fields:
              - { label: 'R', name: 'r', widget: 'text' }
              - { label: 'Javascript', name: 'javascript', widget: 'text' }
              - { label: 'Scala', name: 'scala', widget: 'text' }
              - { label: 'Python', name: 'python', widget: 'text' }
media_folder: "static/images/uploads"
public_folder: "/images/uploads"